version: '3'

services:

  app:
    container_name: app
    build:
      context: ./gameroom
      dockerfile: dockerfile
    env_file:
      - ./gameroom.env
    ports:
      - "5000:5000"
    volumes:
      - ./gameroom/app:/gameroom/app
    links:
      - db

  db:
    container_name: db
    image: mysql:5.7 
    ports:
      - "32000:3306"
    env_file: 
      - ./gameroom.env 
    volumes:
      - ./gameroom/mysql:/docker-entrypoint-initdb.d/:ro 