version: '3'

services:

  app:
    container_name: app
    build:
      context: ./gameroom
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./gameroom/app:/gameroom/app
